name: Bisect Windows x64

on:
  push:
    branches:
      - bisect-x64-build

jobs:
  build-windows-x64:
    runs-on: windows-2022
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29.0'

      - name: Bootstrap vcpkg
        shell: pwsh
        run: ./dependencies/vcpkg/bootstrap-vcpkg.bat

      - name: Configure
        shell: pwsh
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=release -DVCPKG_INSTALL_OPTIONS="--clean-after-build"

      - name: Build Cemu
        shell: pwsh
        run: cmake --build build --config release

      - name: Prepare artifact
        shell: pwsh
        run: Rename-Item bin/Cemu_release.exe Cemu.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cemu-bisect-x64-1
          path: ./bin/Cemu.exe
